[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.dependencies]
insta = { version = "1.46", features = ["yaml", "redactions"] }
anyhow = { version = "1.0" }
actix-web = "4.12"
tracing = "0.1"
