[package]
name = "fhtmx"
version = "0.16.0"
authors = ["Renato Hermoza <rhermoza145@gmail.com>"]
description = "Create html with rust with support for htmx."
documentation = "https://docs.rs/fhtmx"
keywords = ["html", "htmx"]
license = "MIT OR Apache-2.0"
edition = "2024"
include = [
  "/src/**/*",
  "!/src/**/snapshots/*",
  "/LICENSE",
  "/README.md",
  "/CHANGELOG.md",
]
repository = "https://github.com/renato145/fhtmx"

[dependencies]
dyn-clone = "1.0"
htmlescape = "0.3"
indexmap = "2.13"
paste = "1.0"

[dev-dependencies]
googletest = "0.14"
insta = { version = "1.46", features = ["yaml", "redactions"] }
