[package]
name = "fhtmx"
version = "0.16.0"
authors = ["Renato Hermoza <rhermoza145@gmail.com>"]
description = "Create html with rust with support for htmx."
documentation = "https://docs.rs/fhtmx"
keywords = ["html", "htmx"]
license = "MIT OR Apache-2.0"
edition = "2024"
# TODO: update
include = [
  "/src/**/*",
  "!/src/**/snapshots/*",
  "/LICENSE",
  "/README.md",
  "/CHANGELOG.md",
]
repository = "https://github.com/renato145/fhtmx"

[dependencies]
indexmap = { workspace = true }
pastey = "0.2"
uuid = { version = "1.19", features = ["v4"] }

[dev-dependencies]
insta = { workspace = true }
lipsum = "0.9"
