[package]
name = "fhtmx-derive"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["extra-traits"] }
quote = "1.0"
darling = "0.23"
proc-macro2 = "1.0"
